spring:
  datasource:
    username: root
    password: "1234"
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "" #your email
    password: "" #you apps password
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

project:
  poster: posters/

base:
  url: "http://localhost:8080"

debug: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG
    com.sun.mail: DEBUG
    jakarta.mail: DEBUG
